apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsonserver-deployment
  labels:
    app: jsonserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jsonserver
  template:
    metadata:
      labels:
        app: jsonserver
    spec:
      containers:
      - name: jsonserver
        image: theyashwantsoni/jsonserver:1.0.0
        ports:
        - containerPort: 3000
